name:                wumpus
version:             0.1.0.0
github:              "Tientuine/wumpus"
license:             BSD-3-Clause
author:              "Matthew A Johnson"
maintainer:          "Matt.Johnson@marist.edu"
copyright:           "2024 Matthew A Johnson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Tientuine/wumpus#readme>

dependencies:
- base >= 4.8 && < 5
- mtl >= 2.2 && < 2.3
- random >= 1.2.1
- random-shuffle >= 0.0.4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  wumpus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wumpus
    - mtl

tests:
  wumpus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wumpus
    - mtl
